---
title: "flat_dy_birth.Rmd empty"
output: html_document
editor_options:
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
```

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
```

# dy_birth

```{r function-dy_birth}
#' dy_birth
#'
#' @filename fct_dy_birth.R
#'
#' @noRd
#' @param from date date from
#' @param to date date to
#' @param group_by_sex logical wether or not to group by sex
dy_birth <- function(
  from,
  to,
  group_by_sex = FALSE
) {

      if (group_by_sex) {
        prenomsapp::birth_by_year_and_sex |>
          dplyr::filter(.data$year >= from, .data$year <= to) |>
          dplyr::group_by(.data$year, .data$sex) |>
          dplyr::summarise(total = sum(.data$n)) |>
          tidyr::spread(key = .data$sex, value = .data$total) |>
          dygraphs::dygraph()
      } else {
        prenomsapp::birth_by_year |>
          dplyr::filter(.data$year >= from, .data$year <= to) |>
          dplyr::group_by(.data$year) |>
          dplyr::summarise(total = sum(.data$n)) |>
          dygraphs::dygraph()
      }
}
```

```{r examples-dy_birth}
dy_birth(
  1990,
  2010
)
```

```{r tests-dy_birth}
test_that("dy_birth works", {
  res <- dy_birth(
    1990,
    2010
  )
  expect_true(
    inherits(res, "dygraphs")
  )
  expect_true(
    inherits(res, "htmlwidget")
  )
})
```



