---
title: "flat_raw_data.Rmd empty"
output: html_document
editor_options:
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
```

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
```

# raw_data

```{r function-raw_data}
#' raw_data
#'
#' @filename fct_raw_data.R
#'
#' @noRd
#'
#' @examples
raw_data <- function(
  name_choice,
  filter_by_dep = FALSE,
  dep = "01",
  filter_by_sex = FALSE,
  sex_choice = "F"
    ) {
  f <- prenoms::prenoms |>
    dplyr::filter(.data$name == name_choice)
  if (filter_by_sex) {
    f <- f |>
      dplyr::filter(.data$sex == sex_choice)
  }
  if (filter_by_dep) {
    f <- f |>
      dplyr::filter(.data$dpt == dep)
  }

  f |>
    dplyr::group_by(.data$year, .data$name) |>
    dplyr::summarise(total = sum(.data$n)) |>
    dplyr::arrange(.data$year) |>
    DT::datatable()
}

```

```{r examples-raw_data}
raw_data(
  "Colin"
)
```

```{r tests-raw_data}
test_that("raw_data works", {
  res <- raw_data(
    1901
  )
  expect_true(
    inherits(
      res,
      "datatables"
    )
  )
  expect_true(
    inherits(
      res,
      "htmlwidget"
    )
  )
})
```

