# WARNING - Generated by {fusen} from /dev/flat_fct_utils.Rmd: do not edit by hand

test_that("select_a_dep works", {
	expect_true(inherits(select_a_dep, "function"))
	expect_true(
		grepl(
			"shiny-input-container",
			select_a_dep("pif")
		)
	)
	expect_true(
		grepl(
			"pif",
			select_a_dep("pif")
		)
	)
})
