# WARNING - Generated by {fusen} from /dev/flat_raw_data.Rmd: do not edit by hand

test_that("raw_data works", {
	res <- raw_data(
		1901
	)
	expect_true(
		inherits(
			res,
			"datatables"
		)
	)
	expect_true(
		inherits(
			res,
			"htmlwidget"
		)
	)
})
