# WARNING - Generated by {fusen} from /dev/flat_by_dep.Rmd: do not edit by hand

test_that("by_dep works", {
	res <- by_dep(
		61,
		date = c(1902, 1903)
	)
	expect_true(inherits(res, "dygraphs"))
})
