# WARNING - Generated by {fusen} from /dev/flat_top_names.Rmd: do not edit by hand

test_that("top_names works", {
	res <- top_names(
		1901
	)
	expect_true(
		inherits(
			res,
			"plotly"
		)
	)
	expect_true(
		inherits(
			res,
			"htmlwidget"
		)
	)
})
