# WARNING - Generated by {fusen} from /dev/flat_fct_utils.Rmd: do not edit by hand

test_that("capwords works", {
  expect_equal(
    capwords("COLIN"),
    "Colin"
  )
})

test_that("slider_date_prenoms works", {
  expect_true(
    inherits(slider_date_prenoms, "function")
  )
  expect_true(
    grepl(
      "shiny-input-container",
      slider_date_prenoms("pif")
    )
  )
  expect_true(
    grepl(
      "pif",
      slider_date_prenoms("pif")
    )
  )
})

test_that("group_by_sex works", {
  expect_true(inherits(group_by_sex, "function"))
  expect_true(
    grepl(
      "shiny-input-container",
      group_by_sex("pif")
    )
  )
  expect_true(
    grepl(
      "pif",
      group_by_sex("pif")
    )
  )
})

test_that("filter_by_dep works", {
  expect_true(inherits(filter_by_dep, "function"))
  expect_true(
    grepl(
      "shiny-input-container",
      filter_by_dep("pif")
    )
  )
  expect_true(
    grepl(
      "pif",
      filter_by_dep("pif")
    )
  )
})

test_that("select_a_name works", {
  expect_true(inherits(select_a_name, "function"))
  expect_true(
    grepl(
      "shiny-input-container",
      select_a_name("pif")
    )
  )
  expect_true(
    grepl(
      "pif",
      select_a_name("pif")
    )
  )
})

test_that("select_a_dep works", {
  expect_true(inherits(select_a_dep, "function"))
  expect_true(
    grepl(
      "shiny-input-container",
      select_a_dep("pif")
    )
  )
  expect_true(
    grepl(
      "pif",
      select_a_dep("pif")
    )
  )
})

test_that("render_button works", {
  expect_true(inherits(render_button, "function"))
  expect_true(
    grepl(
      "action-button",
      render_button("pif")
    )
  )
  expect_true(
    grepl(
      "pif",
      render_button("pif")
    )
  )
})
