# WARNING - Generated by {fusen} from /dev/flat_fct_utils.Rmd: do not edit by hand

test_that("render_button works", {
  expect_true(inherits(render_button, "function"))
  expect_true(
    grepl(
      "action-button",
      render_button("pif")
    )
  )
  expect_true(
    grepl(
      "pif",
      render_button("pif")
    )
  )
})
