# WARNING - Generated by {fusen} from /dev/flat_mod_1.Rmd: do not edit by hand

test_that("display_mod_1_dygraph works", {
	res <- prenoms::prenoms |>
		dplyr::filter(name == "Colin") |>
		display_mod_1_dygraph()
	expect_true(inherits(res, "dygraphs"))
})
