# WARNING - Generated by {fusen} from /dev/flat_dy_birth.Rmd: do not edit by hand

test_that("dy_birth works", {
  res <- dy_birth(
    1990,
    2010
  )
  expect_true(
    inherits(res, "dygraphs")
  )
  expect_true(
    inherits(res, "htmlwidget")
  )
})
