# WARNING - Generated by {fusen} from /dev/flat_fct_utils.Rmd: do not edit by hand

#' fct_utils
#'
#' @noRd
#'
#' @param s character vector
#' @param strict logical (default: FALSE)
#' @examples
#' capwords("COLIN")
capwords <- function(s, strict = FALSE) {
	cap <- function(s) {
		paste(
			toupper(
				substring(s, 1, 1)
			),
			{
				s <- substring(s, 2)
				if (strict) tolower(s) else s
			},
			sep = "",
			collapse = " "
		)
	}
	s <- tolower(s)
	sapply(strsplit(s, split = " "), cap, USE.NAMES = !is.null(names(s)))
}

#' Title
#'
#'
#' @noRd
#' @examples
#' filter_by_dep("pif")
filter_by_dep <- function(id) {
	checkboxInput(
		id,
		"Filter by department?",
		FALSE
	)
}
#' @noRd
filter_by_sex <- function(id) {
	checkboxInput(
		id,
		"Filter by sex?",
		FALSE
	)
}

#' Group By sex checkbox
#'
#' @noRd
#'
#' @examples
#' group_by_sex("pif")
group_by_sex <- function(
	id) {
	shiny::checkboxInput(
		id,
		"Group by sex?",
		FALSE
	)
}

#' render_button
#'
#' @noRd
#' @examples
#' render_button("pif")
render_button <- function(id) {
	sk_button(
		id,
		"Render",
		icon = icon("refresh")
	)
}

#' Title
#'
#' @noRd
#' @examples
#' select_a_dep("pif")
select_a_dep <- function(id) {
	selectInput(
		id,
		"Department",
		choices = prenomsapp::deps
	)
}
select_a_sex <- function(id) {
	selectInput(
		id,
		"Sex",
		choices = c("M", "F")
	)
}

#' select_a_name
#'
#' @noRd
#' @examples
#' select_a_name("pif")
select_a_name <- function(id) {
	textInput(
		id,
		"Name",
		value = "Colin"
	)
}

#' ui element for selecting in prenoms
#'
#' @noRd
#'
#' @examples
#' slider_date_prenoms("pif")
select_date_prenoms <- function(
	id) {
	shiny::selectInput(
		id,
		"Year:",
		choices = 1900:2017,
		selected = 1900
	)
}

#' @noRd
#'
slider_date_prenoms <- function(
	id) {
	shiny::sliderInput(
		id,
		"Dates:",
		value = c(
			min(prenomsapp::prenoms_dates),
			max(prenomsapp::prenoms_dates)
		),
		min = min(prenomsapp::prenoms_dates),
		max = max(prenomsapp::prenoms_dates)
	)
}
