# WARNING - Generated by {fusen} from /dev/flat_dy_birth.Rmd: do not edit by hand

#' dy_birth
#'
#'
#'
#' @noRd
#' @param from date date from
#' @param to date date to
#' @param group_by_sex logical wether or not to group by sex
#' @examples
#' dy_birth(
#'   1990,
#'   2010
#' )
dy_birth <- function(
  from,
  to,
  group_by_sex = FALSE
    ) {
  if (group_by_sex) {
    prenomsapp::birth_by_year_and_sex |>
      dplyr::filter(.data$year >= from, .data$year <= to) |>
      dplyr::group_by(.data$year, .data$sex) |>
      dplyr::summarise(total = sum(.data$n)) |>
      tidyr::spread(key = .data$sex, value = .data$total) |>
      dygraphs::dygraph()
  } else {
    prenomsapp::birth_by_year |>
      dplyr::filter(.data$year >= from, .data$year <= to) |>
      dplyr::group_by(.data$year) |>
      dplyr::summarise(total = sum(.data$n)) |>
      dygraphs::dygraph()
  }
}
