# WARNING - Generated by {fusen} from /dev/flat_mod_1.Rmd: do not edit by hand

#' display_mod_1_dygraph
#'
#'
#' @noRd
#' @examples
#' prenoms::prenoms |>
#'   dplyr::filter(name == "Colin") |>
#'   display_mod_1_dygraph()
display_mod_1_dygraph <- function(dataset) {
  dataset |>
    dplyr::group_by(.data$year, .data$name) |>
    dplyr::summarise(total = sum(.data$n)) |>
    tidyr::spread(key = .data$name, value = .data$total) |>
    dygraphs::dygraph()
}
