# WARNING - Generated by {fusen} from /dev/flat_fct_utils.Rmd: do not edit by hand

#' Group By sex checkbox
#'
#' @noRd
#' @examples
#' group_by_sex("pif")
group_by_sex <- function(
	id) {
	shiny::checkboxInput(
		id,
		"Group by sex?",
		FALSE
	)
}
